import { useState, useMemo, useEffect, useCallback } from 'react';
import { useHistory } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { RefreshCw, Trophy, Zap, Flame, X } from 'lucide-react';
import { WorkoutTemplateSelector } from './WorkoutTemplateSelector';
import { ProgramControls } from './ProgramControls';
import { WorkoutCard } from '../WorkoutCard';
import { useQueryClient } from '@tanstack/react-query';
import { usePrograms, useRegeneratePlan, useStartSession, useTodayWorkout } from '../../hooks/useApi';
import { PlanGeneratingOverlay } from '../ui';
import { ProgramDashboardContentSkeleton } from './ProgramDashboardSkeleton';
import type { ProgramResource, WorkoutTemplateResource } from '../../types/api';

const PROGRAM_MILESTONE_THRESHOLDS = [20, 50, 75] as const;

function milestoneStorageKey(programId: number): string {
  return `milestone_celebrated_${programId}`;
}

interface ProgramDashboardProps {
  onStartWorkout: () => void;
}

export function ProgramDashboard({ onStartWorkout }: ProgramDashboardProps) {
  const history = useHistory();
  const { data: programs = [], isLoading: isProgramsLoading } = usePrograms();
  const startSession = useStartSession();
  const { data: todayWorkout } = useTodayWorkout();
  const queryClient = useQueryClient();
  const regeneratePlan = useRegeneratePlan();
  const [isGenerating, setIsGenerating] = useState(false);
  const [milestoneDismissVersion, setMilestoneDismissVersion] = useState(0);

  // Get active program
  const activeProgram = useMemo(() => {
    return programs.find((program: ProgramResource) => program.is_active) || null;
  }, [programs]);

  // The auto-generated program to drive ProgramControls — prefer the active one, fall back to any inactive one
  const autoGeneratedProgram = useMemo(() => {
    return (
      programs.find((p: ProgramResource) => p.is_auto_generated && p.is_active) ||
      programs.find((p: ProgramResource) => p.is_auto_generated) ||
      null
    );
  }, [programs]);

  // Prefer next_workout's week so the dashboard reflects program progression
  const displayWeekNumber = useMemo(() => {
    return activeProgram?.next_workout?.week_number ?? activeProgram?.current_active_week ?? 1;
  }, [activeProgram]);

  // Get workout templates for the displayed week
  const activeWeekWorkouts = useMemo(() => {
    if (!activeProgram?.workout_templates) return [];
    const currentWeek = displayWeekNumber;
    return activeProgram.workout_templates
      .filter((template: WorkoutTemplateResource) => template.week_number === currentWeek)
      .sort((a: WorkoutTemplateResource, b: WorkoutTemplateResource) => a.order_index - b.order_index);
  }, [activeProgram, displayWeekNumber]);

  // Default to first workout in displayed week, or next_workout if available
  const defaultSelectedId = useMemo(() => {
    if (activeProgram?.next_workout && activeWeekWorkouts.some((w: WorkoutTemplateResource) => w.id === activeProgram.next_workout?.id)) {
      return activeProgram.next_workout.id;
    }
    return activeWeekWorkouts.length > 0 ? activeWeekWorkouts[0].id : null;
  }, [activeProgram, activeWeekWorkouts]);

  const [selectedTemplateId, setSelectedTemplateId] = useState<number | null>(() => defaultSelectedId);

  // Sync selection when data loads for the first time (programs arrive after mount)
  // or when the active program changes (e.g. after regeneration)
  useEffect(() => {
    if (defaultSelectedId !== null) {
      setSelectedTemplateId(defaultSelectedId);
    }
  }, [defaultSelectedId]);
  const handleCompletedDayClick = (sessionId: number) => {
    history.push(`/sessions/${sessionId}`, { navPage: 'dashboard' });
  };

  // Get selected workout template
  const selectedWorkout = useMemo(() => {
    if (!selectedTemplateId) return null;
    return activeWeekWorkouts.find((w: WorkoutTemplateResource) => w.id === selectedTemplateId) || null;
  }, [activeWeekWorkouts, selectedTemplateId]);

  // Use selected workout for display
  const displayWorkout = selectedWorkout;

  // Get week info from active program
  const weekInfo = useMemo(() => {
    if (!activeProgram) return null;
    const currentWeek = displayWeekNumber;
    const totalWeeks = activeProgram.duration_weeks ?? 1;
    return {
      current: currentWeek,
      total: totalWeeks
    };
  }, [activeProgram, displayWeekNumber]);

  const handleExerciseClick = (exerciseName: string) => {
    history.push(`/exercises/${encodeURIComponent(exerciseName)}`);
  };

  const handleEditWorkout = (templateId: number) => {
    history.push(`/workouts/${templateId}/exercises`, { returnPath: '/dashboard?type=programs' });
  };

  // Check if there's an active (in-progress) session for the currently selected template
  const activeSessionForSelected = useMemo(() => {
    if (!selectedTemplateId || !todayWorkout?.session) return null;
    const session = todayWorkout.session;
    if (!session.completed_at && session.workout_template_id === selectedTemplateId) {
      return session;
    }
    return null;
  }, [selectedTemplateId, todayWorkout]);

  const handleStartSelectedWorkout = async () => {
    if (activeSessionForSelected?.id) {
      history.push(`/session/${activeSessionForSelected.id}`);
      return;
    }

    const templateId = selectedTemplateId ?? activeProgram?.next_workout?.id;
    if (!templateId) {
      onStartWorkout();
      return;
    }

    try {
      const response = await startSession.mutateAsync(templateId);
      const session = response.data?.session || response.data;
      if (session?.id) {
        if (!session.performed_at) {
          history.push(`/generate-workout/preview/${session.id}`);
        } else {
          history.push(`/session/${session.id}`);
        }
      }
    } catch (error) {
      console.error('Failed to start workout:', error);
    }
  };

  const handleGenerateFresh = async () => {
    setIsGenerating(true);
    try {
      await regeneratePlan.mutateAsync();
      await queryClient.refetchQueries({ queryKey: ['programs'] });
    } catch (error) {
      console.error('Failed to generate plan:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const inactiveNonAutoPrograms = useMemo(() => {
    return programs.filter((p: ProgramResource) => !p.is_active && !p.is_auto_generated);
  }, [programs]);

  const isPlanComplete = useMemo(() => {
    if (!activeProgram) return false;
    return (
      activeProgram.next_workout === null &&
      (activeProgram.progress_percentage ?? 0) > 0
    );
  }, [activeProgram]);

  const pendingMilestone = useMemo(() => {
    if (!activeProgram?.id || isPlanComplete) return null;
    const pct = activeProgram.progress_percentage;
    if (pct == null || pct < PROGRAM_MILESTONE_THRESHOLDS[0]) return null;
    const storageKey = milestoneStorageKey(activeProgram.id);
    const lastCelebrated = Number(localStorage.getItem(storageKey) ?? 0);
    const reached = PROGRAM_MILESTONE_THRESHOLDS.filter((m) => pct >= m);
    const next = reached.find((m) => m > lastCelebrated);
    return next ?? null;
  }, [activeProgram, isPlanComplete, milestoneDismissVersion]);

  const handleDismissMilestone = useCallback(() => {
    if (!activeProgram?.id || pendingMilestone == null) return;
    localStorage.setItem(milestoneStorageKey(activeProgram.id), String(pendingMilestone));
    setMilestoneDismissVersion((v) => v + 1);
  }, [activeProgram?.id, pendingMilestone]);

  const planCompleteStats = useMemo(() => {
    const templates = activeProgram?.workout_templates ?? [];
    let workoutsCompleted = 0;
    let totalSets = 0;
    const uniqueExerciseNames = new Set<string>();

    for (const t of templates) {
      if (t.last_completed_session_id !== null) workoutsCompleted += 1;
      const exercises = t.exercises ?? [];
      for (const e of exercises) {
        uniqueExerciseNames.add(e.name);
        totalSets += e.pivot?.target_sets ?? 0;
      }
    }

    return {
      durationWeeks: activeProgram?.duration_weeks ?? 0,
      workoutsCompleted,
      totalWorkouts: templates.length,
      uniqueExercises: uniqueExerciseNames.size,
      totalSets,
      progressPercentage: activeProgram?.progress_percentage ?? 0,
    };
  }, [activeProgram]);

  if (isProgramsLoading) {
    return <ProgramDashboardContentSkeleton />;
  }

  return (
    <div className="pb-32">
      {/* Always show ProgramControls whenever there's any auto-generated program */}
      {autoGeneratedProgram && (
        <ProgramControls activeProgram={autoGeneratedProgram} />
      )}

      {isGenerating && <PlanGeneratingOverlay fullscreen />}

      {!activeProgram && (
        <div
          className="rounded-2xl p-6 mb-6 space-y-4"
          style={{ backgroundColor: 'var(--color-bg-surface)' }}
        >
          <p className="text-center font-semibold" style={{ color: 'var(--color-text-primary)' }}>
            No active program
          </p>

          {/* Inactive non-auto programs the user can activate */}
          {inactiveNonAutoPrograms.length > 0 && (
            <div className="space-y-2">
              {inactiveNonAutoPrograms.map((program: ProgramResource) => (
                <button
                  key={program.id}
                  onClick={() => history.push(`/programs/${program.id}`)}
                  className="w-full flex items-center justify-between px-4 py-3 rounded-xl border text-sm font-semibold"
                  style={{
                    backgroundColor: 'var(--color-bg-elevated)',
                    color: 'var(--color-text-primary)',
                    borderColor: 'var(--color-border)',
                  }}
                >
                  <span>{program.name}</span>
                  <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>View →</span>
                </button>
              ))}
            </div>
          )}

          {/* Generate a fresh personalized plan */}
          <button
            onClick={handleGenerateFresh}
            disabled={isGenerating || regeneratePlan.isPending}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl font-semibold disabled:opacity-60 disabled:cursor-not-allowed"
            style={{
              backgroundColor: 'var(--color-primary)',
              color: 'var(--color-text-button)',
            }}
          >
            {isGenerating || regeneratePlan.isPending ? (
              <RefreshCw size={16} className="animate-spin" />
            ) : (
              <Zap size={16} />
            )}
            Generate personalized plan
          </button>
        </div>
      )}

      {activeProgram && (
        <>
          {/* Workout Template Selector - hidden when plan is complete */}
          {!isPlanComplete && activeWeekWorkouts.length > 0 && (
            <div className="mb-6 -mx-1 px-1">
              <WorkoutTemplateSelector
                templates={activeWeekWorkouts}
                selectedTemplateId={selectedTemplateId}
                onTemplateSelect={setSelectedTemplateId}
                nextWorkout={activeProgram.next_workout ?? null}
                onCompletedDayClick={handleCompletedDayClick}
              />
            </div>
          )}

          {/* Week Indicator */}
          {weekInfo && (
            <div className="text-center mb-4">
              <p
                className="font-semibold text-xs uppercase tracking-wider"
                style={{ color: 'var(--color-primary)' }}
              >
                Week {weekInfo.current}/{weekInfo.total}
                {activeProgram.name && ` - ${activeProgram.name}`}
              </p>
            </div>
          )}

          {/* Mid-program milestone (25% / 50% / 75%) */}
          <AnimatePresence>
            {!isPlanComplete && pendingMilestone != null && (
              <motion.div
                key={pendingMilestone}
                initial={{ opacity: 0, y: -8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -8 }}
                transition={{ duration: 0.25 }}
                className="mb-4 rounded-2xl border p-4 flex gap-3 items-start"
                style={{
                  backgroundColor: 'color-mix(in srgb, var(--color-primary) 12%, var(--color-bg-surface))',
                  borderColor: 'var(--color-border)',
                }}
                role="status"
              >
                <div
                  className="flex shrink-0 items-center justify-center w-11 h-11 rounded-full"
                  style={{
                    backgroundColor: 'color-mix(in srgb, var(--color-primary) 25%, transparent)',
                    color: 'var(--color-primary)',
                  }}
                >
                  <Flame size={22} strokeWidth={2} />
                </div>
                <div className="min-w-0 flex-1">
                  <p
                    className="text-sm font-bold mb-0.5"
                    style={{ color: 'var(--color-text-primary)' }}
                  >
                    {pendingMilestone}% milestone
                  </p>
                  <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
                    You&apos;re {pendingMilestone}% through your plan — keep it up!
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleDismissMilestone}
                  className="shrink-0 rounded-full p-1.5 transition-colors hover:bg-white/10"
                  style={{ color: 'var(--color-text-secondary)' }}
                  aria-label="Dismiss milestone"
                >
                  <X size={18} />
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Plan complete / Workout Card / empty */}
          {isPlanComplete ? (
            <div
              className="rounded-2xl p-6 mb-6 text-center space-y-5"
              style={{ backgroundColor: 'var(--color-bg-surface)' }}
            >
              <div className="flex justify-center">
                <div
                  className="flex items-center justify-center w-16 h-16 rounded-full"
                  style={{
                    backgroundColor: 'var(--color-bg-elevated)',
                    color: 'var(--color-primary)',
                  }}
                >
                  <Trophy size={32} strokeWidth={1.75} />
                </div>
              </div>
              <div>
                <h2
                  className="text-xl font-bold mb-2"
                  style={{ color: 'var(--color-text-primary)' }}
                >
                  Plan complete!
                </h2>
                <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
                  You finished all {planCompleteStats.durationWeeks} week
                  {planCompleteStats.durationWeeks !== 1 ? 's' : ''} of{' '}
                  <span className="font-semibold" style={{ color: 'var(--color-text-primary)' }}>
                    {activeProgram.name}
                  </span>
                  .
                </p>
              </div>

              <div className="grid grid-cols-2 gap-3 text-left">
                {[
                  {
                    label: 'Weeks',
                    value: String(planCompleteStats.durationWeeks),
                  },
                  {
                    label: 'Workouts',
                    value:
                      planCompleteStats.totalWorkouts > 0
                        ? `${planCompleteStats.workoutsCompleted}/${planCompleteStats.totalWorkouts}`
                        : String(planCompleteStats.workoutsCompleted),
                  },
                  {
                    label: 'Exercises',
                    value: String(planCompleteStats.uniqueExercises),
                  },
                  {
                    label: 'Sets',
                    value: String(planCompleteStats.totalSets),
                  },
                ].map((tile) => (
                  <div
                    key={tile.label}
                    className="rounded-xl px-4 py-3 border"
                    style={{
                      backgroundColor: 'var(--color-bg-elevated)',
                      borderColor: 'var(--color-border)',
                    }}
                  >
                    <p
                      className="text-xs font-semibold uppercase tracking-wide mb-1"
                      style={{ color: 'var(--color-text-secondary)' }}
                    >
                      {tile.label}
                    </p>
                    <p className="text-lg font-bold" style={{ color: 'var(--color-text-primary)' }}>
                      {tile.value}
                    </p>
                  </div>
                ))}
              </div>

              {planCompleteStats.progressPercentage > 0 && (
                <p className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>
                  Progress:{' '}
                  <span className="font-semibold" style={{ color: 'var(--color-primary)' }}>
                    {planCompleteStats.progressPercentage}%
                  </span>
                </p>
              )}

              {activeProgram.is_auto_generated && (
                <button
                  type="button"
                  onClick={handleGenerateFresh}
                  disabled={isGenerating || regeneratePlan.isPending}
                  className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl font-semibold disabled:opacity-60 disabled:cursor-not-allowed"
                  style={{
                    backgroundColor: 'var(--color-primary)',
                    color: 'var(--color-text-button)',
                  }}
                >
                  {isGenerating || regeneratePlan.isPending ? (
                    <RefreshCw size={16} className="animate-spin" />
                  ) : (
                    <Zap size={16} />
                  )}
                  Generate new plan
                </button>
              )}
            </div>
          ) : displayWorkout ? (
            <div className="mb-6">
              <WorkoutCard
                template={displayWorkout}
                title={selectedWorkout?.name || "WORKOUT"}
                onStartNextWorkout={handleStartSelectedWorkout}
                showStartButton={true}
                startButtonText={
                  activeSessionForSelected
                    ? 'CONTINUE WORKOUT'
                    : selectedTemplateId
                      ? 'START WORKOUT'
                      : 'NO WORKOUTS AVAILABLE'
                }
                startButtonDisabled={!selectedTemplateId && !activeSessionForSelected}
                onExerciseClick={handleExerciseClick}
                onEditWorkout={handleEditWorkout}
              />
            </div>
          ) : (
            <div
              className="rounded-2xl p-6 mb-6 text-center"
              style={{
                backgroundColor: 'var(--color-bg-surface)',
                color: 'var(--color-text-secondary)',
              }}
            >
              <p>No workouts available for this week</p>
            </div>
          )}
        </>
      )}

    </div>
  );
}
