import React, { useState, useMemo, useEffect } from 'react';
import { useHistory } from 'react-router-dom';
import { RefreshCw, Zap } from 'lucide-react';
import { WorkoutTemplateSelector } from './WorkoutTemplateSelector';
import { ProgramControls } from './ProgramControls';
import { WorkoutCard } from '../WorkoutCard';
import { SessionDetailModal } from '../SessionDetailModal';
import { useQueryClient } from '@tanstack/react-query';
import { usePrograms, useRegeneratePlan, useStartSession, useTodayWorkout } from '../../hooks/useApi';
import { PlanGeneratingOverlay } from '../ui';
import type { ProgramResource, WorkoutTemplateResource } from '../../types/api';

interface ProgramDashboardProps {
  onStartWorkout: () => void;
}

export function ProgramDashboard({ onStartWorkout }: ProgramDashboardProps) {
  const history = useHistory();
  const { data: programs = [], isLoading: isProgramsLoading } = usePrograms();
  const startSession = useStartSession();
  const { data: todayWorkout } = useTodayWorkout();
  const queryClient = useQueryClient();
  const regeneratePlan = useRegeneratePlan();
  const [isGenerating, setIsGenerating] = useState(false);

  // Get active program
  const activeProgram = useMemo(() => {
    return programs.find((program: ProgramResource) => program.is_active) || null;
  }, [programs]);

  // The auto-generated program to drive ProgramControls — prefer the active one, fall back to any inactive one
  const autoGeneratedProgram = useMemo(() => {
    return (
      programs.find((p: ProgramResource) => p.is_auto_generated && p.is_active) ||
      programs.find((p: ProgramResource) => p.is_auto_generated) ||
      null
    );
  }, [programs]);

  // Prefer next_workout's week so the dashboard reflects program progression
  const displayWeekNumber = useMemo(() => {
    return activeProgram?.next_workout?.week_number ?? activeProgram?.current_active_week ?? 1;
  }, [activeProgram]);

  // Get workout templates for the displayed week
  const activeWeekWorkouts = useMemo(() => {
    if (!activeProgram?.workout_templates) return [];
    const currentWeek = displayWeekNumber;
    return activeProgram.workout_templates
      .filter((template: WorkoutTemplateResource) => template.week_number === currentWeek)
      .sort((a: WorkoutTemplateResource, b: WorkoutTemplateResource) => a.order_index - b.order_index);
  }, [activeProgram, displayWeekNumber]);

  // Default to first workout in displayed week, or next_workout if available
  const defaultSelectedId = useMemo(() => {
    if (activeProgram?.next_workout && activeWeekWorkouts.some((w: WorkoutTemplateResource) => w.id === activeProgram.next_workout?.id)) {
      return activeProgram.next_workout.id;
    }
    return activeWeekWorkouts.length > 0 ? activeWeekWorkouts[0].id : null;
  }, [activeProgram, activeWeekWorkouts]);

  const [selectedTemplateId, setSelectedTemplateId] = useState<number | null>(() => defaultSelectedId);

  // Sync selection when data loads for the first time (programs arrive after mount)
  // or when the active program changes (e.g. after regeneration)
  useEffect(() => {
    if (defaultSelectedId !== null) {
      setSelectedTemplateId(defaultSelectedId);
    }
  }, [defaultSelectedId]);
  const [completedSessionId, setCompletedSessionId] = useState<number | null>(null);
  const [isSessionModalOpen, setIsSessionModalOpen] = useState(false);

  const handleCompletedDayClick = (sessionId: number) => {
    setCompletedSessionId(sessionId);
    setIsSessionModalOpen(true);
  };

  // Get selected workout template
  const selectedWorkout = useMemo(() => {
    if (!selectedTemplateId) return null;
    return activeWeekWorkouts.find((w: WorkoutTemplateResource) => w.id === selectedTemplateId) || null;
  }, [activeWeekWorkouts, selectedTemplateId]);

  // Use selected workout for display
  const displayWorkout = selectedWorkout;

  // Get week info from active program
  const weekInfo = useMemo(() => {
    if (!activeProgram) return null;
    const currentWeek = displayWeekNumber;
    const totalWeeks = activeProgram.duration_weeks ?? 1;
    return {
      current: currentWeek,
      total: totalWeeks
    };
  }, [activeProgram, displayWeekNumber]);

  const handleExerciseClick = (exerciseName: string) => {
    history.push(`/exercises/${encodeURIComponent(exerciseName)}`);
  };

  const handleEditWorkout = (templateId: number) => {
    history.push(`/workouts/${templateId}/exercises`, { returnPath: '/dashboard?type=programs' });
  };

  // Check if next_workout has an active session
  const nextWorkoutActiveSession = useMemo(() => {
    if (!activeProgram?.next_workout?.id || !todayWorkout?.session) return null;
    const session = todayWorkout.session;
    if (!session.completed_at && session.workout_template_id === activeProgram.next_workout.id) {
      return session;
    }
    return null;
  }, [activeProgram, todayWorkout]);

  const handleStartNextWorkout = async () => {
    // If there's an active session for next_workout, continue it
    if (nextWorkoutActiveSession?.id) {
      history.push(`/session/${nextWorkoutActiveSession.id}`);
      return;
    }

    if (!activeProgram?.next_workout?.id) {
      // Fallback to onStartWorkout if no next_workout
      onStartWorkout();
      return;
    }

    try {
      const response = await startSession.mutateAsync(activeProgram.next_workout.id);
      const session = response.data?.session || response.data;
      if (session?.id) {
        // Check if draft (performed_at is null)
        if (!session.performed_at) {
          // Navigate to preview page to continue setup
          history.push(`/generate-workout/preview/${session.id}`);
        } else {
          // Active session - continue workout
          history.push(`/session/${session.id}`);
        }
      }
    } catch (error) {
      console.error('Failed to start next workout:', error);
    }
  };

  const handleGenerateFresh = async () => {
    setIsGenerating(true);
    try {
      await regeneratePlan.mutateAsync();
      await queryClient.refetchQueries({ queryKey: ['programs'] });
    } catch (error) {
      console.error('Failed to generate plan:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const inactiveNonAutoPrograms = useMemo(() => {
    return programs.filter((p: ProgramResource) => !p.is_active && !p.is_auto_generated);
  }, [programs]);

  if (isProgramsLoading) {
    return (
      <div className="pb-32">
        <div className="flex flex-col items-center justify-center py-12">
          <div 
            className="w-10 h-10 border-4 border-t-transparent rounded-full animate-spin mb-4"
            style={{ borderColor: 'var(--color-primary)', borderTopColor: 'transparent' }}
          />
          <p className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
            Loading...
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="pb-32">
      {/* Always show ProgramControls whenever there's any auto-generated program */}
      {autoGeneratedProgram && (
        <ProgramControls activeProgram={autoGeneratedProgram} />
      )}

      {isGenerating && <PlanGeneratingOverlay fullscreen />}

      {!activeProgram && (
        <div
          className="rounded-2xl p-6 mb-6 space-y-4"
          style={{ backgroundColor: 'var(--color-bg-surface)' }}
        >
          <p className="text-center font-semibold" style={{ color: 'var(--color-text-primary)' }}>
            No active program
          </p>

          {/* Inactive non-auto programs the user can activate */}
          {inactiveNonAutoPrograms.length > 0 && (
            <div className="space-y-2">
              {inactiveNonAutoPrograms.map((program: ProgramResource) => (
                <button
                  key={program.id}
                  onClick={() => history.push(`/programs/${program.id}`)}
                  className="w-full flex items-center justify-between px-4 py-3 rounded-xl border text-sm font-semibold"
                  style={{
                    backgroundColor: 'var(--color-bg-elevated)',
                    color: 'var(--color-text-primary)',
                    borderColor: 'var(--color-border)',
                  }}
                >
                  <span>{program.name}</span>
                  <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>View →</span>
                </button>
              ))}
            </div>
          )}

          {/* Generate a fresh personalized plan */}
          <button
            onClick={handleGenerateFresh}
            disabled={isGenerating || regeneratePlan.isPending}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl font-semibold disabled:opacity-60 disabled:cursor-not-allowed"
            style={{
              backgroundColor: 'var(--color-primary)',
              color: 'var(--color-text-button)',
            }}
          >
            {isGenerating || regeneratePlan.isPending ? (
              <RefreshCw size={16} className="animate-spin" />
            ) : (
              <Zap size={16} />
            )}
            Generate personalized plan
          </button>
        </div>
      )}

      {activeProgram && (
        <>
          {/* Workout Template Selector - Shows workouts for active week */}
          {activeWeekWorkouts.length > 0 && (
            <div className="mb-6 -mx-1 px-1">
              <WorkoutTemplateSelector
                templates={activeWeekWorkouts}
                selectedTemplateId={selectedTemplateId}
                onTemplateSelect={setSelectedTemplateId}
                nextWorkout={activeProgram.next_workout ?? null}
                onCompletedDayClick={handleCompletedDayClick}
              />
            </div>
          )}

          {/* Week Indicator */}
          {weekInfo && (
            <div className="text-center mb-4">
              <p
                className="font-semibold text-xs uppercase tracking-wider"
                style={{ color: 'var(--color-primary)' }}
              >
                Week {weekInfo.current}/{weekInfo.total}
                {activeProgram.name && ` - ${activeProgram.name}`}
              </p>
            </div>
          )}

          {/* Workout Card */}
          {displayWorkout ? (
            <div className="mb-6">
              <WorkoutCard
                template={displayWorkout}
                title={selectedWorkout?.name || "WORKOUT"}
                onStartNextWorkout={handleStartNextWorkout}
                showStartButton={true}
                startButtonText={
                  nextWorkoutActiveSession
                    ? 'CONTINUE WORKOUT'
                    : activeProgram.next_workout
                      ? 'START WORKOUT'
                      : 'NO WORKOUTS AVAILABLE'
                }
                startButtonDisabled={!activeProgram.next_workout && !nextWorkoutActiveSession}
                onExerciseClick={handleExerciseClick}
                onEditWorkout={handleEditWorkout}
              />
            </div>
          ) : (
            <div
              className="rounded-2xl p-6 mb-6 text-center"
              style={{
                backgroundColor: 'var(--color-bg-surface)',
                color: 'var(--color-text-secondary)',
              }}
            >
              <p>No workouts available for this week</p>
            </div>
          )}
        </>
      )}

      <SessionDetailModal
        isOpen={isSessionModalOpen}
        onClose={() => {
          setIsSessionModalOpen(false);
          setCompletedSessionId(null);
        }}
        sessionId={completedSessionId}
      />
    </div>
  );
}
