import { useEffect, useMemo, useState } from 'react'
import {
  ActivityIndicator,
  Alert,
  ScrollView,
  Text,
  TouchableOpacity,
  View,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Image } from 'expo-image'
import { LinearGradient } from 'expo-linear-gradient'
import { useNavigation } from '@react-navigation/native'
import type { NativeStackNavigationProp } from '@react-navigation/native-stack'
import {
  Calendar,
  ChevronRight,
  Clock,
  Dumbbell,
  Play,
  Plus,
  RefreshCw,
  Trophy,
  Zap,
} from 'lucide-react-native'
import {
  estimateWorkoutDuration,
  useBrowsableRoutines,
  usePlans,
  usePrograms,
  useProfile,
  useRegeneratePlan,
  useStartSession,
  useUpdateProfile,
} from '@fit-nation/shared'
import type {
  FitnessGoal,
  ProgramResource,
  TrainingExperience,
  WorkoutTemplateResource,
} from '@fit-nation/shared'

import { useAuth } from '../../context/AuthContext'
import { useTheme } from '../../context/ThemeContext'

import { Card } from '../../components/ui/Card'
import { FilterChip } from '../../components/ui/FilterChip'
import { GradientText } from '../../components/ui/GradientText'
import { PlanTypeSwitcher, type PlanType } from '../../components/ui/PlanTypeSwitcher'
import { SkeletonBox } from '../../components/ui/SkeletonBox'
import { WorkoutCard } from '../../components/ui/WorkoutCard'
import { WorkoutTemplateSelector } from '../../components/ui/WorkoutTemplateSelector'

import type { AppStackParamList } from '../../navigation/types'

type Nav = NativeStackNavigationProp<AppStackParamList>

const GOAL_OPTIONS: Array<{ value: FitnessGoal; label: string }> = [
  { value: 'fat_loss', label: 'Fat Loss' },
  { value: 'muscle_gain', label: 'Muscle Gain' },
  { value: 'strength', label: 'Strength' },
  { value: 'general_fitness', label: 'General Fitness' },
]

const EXPERIENCE_OPTIONS: Array<{ value: TrainingExperience; label: string }> = [
  { value: 'beginner', label: 'Beginner' },
  { value: 'intermediate', label: 'Intermediate' },
  { value: 'advanced', label: 'Advanced' },
]

const DAYS_OPTIONS: Array<{ value: number; label: string }> = [1, 2, 3, 4, 5, 6, 7].map((d) => ({
  value: d,
  label: `${d} day${d > 1 ? 's' : ''}`,
}))

const DURATION_OPTIONS: Array<{ value: number; label: string }> = [
  { value: 30, label: '20-30 min' },
  { value: 45, label: '30-45 min' },
  { value: 60, label: '45-60 min' },
  { value: 90, label: '60-90 min' },
  { value: 120, label: '90+ min' },
]

export function DashboardScreen() {
  const { colors } = useTheme()
  const { user } = useAuth()
  const navigation = useNavigation<Nav>()
  const [activeTab, setActiveTab] = useState<PlanType>('programs')
  const [selectedTemplateId, setSelectedTemplateId] = useState<number | null>(null)
  const [isRegenerating, setIsRegenerating] = useState(false)

  const { data: programs = [], isLoading: isProgramsLoading } = usePrograms()
  const { data: plans = [], isLoading: isPlansLoading } = usePlans()
  const { data: browsableRoutines = [] } = useBrowsableRoutines()
  const { data: profileData } = useProfile()
  const regeneratePlan = useRegeneratePlan()
  const startSession = useStartSession()
  const updateProfile = useUpdateProfile()

  const profile = profileData?.profile ?? null
  const partnerName = user?.partner?.name || 'Fit Nation'
  const partnerLogo = user?.partner?.visual_identity?.logo || null

  // ─── Programs tab ───
  const activeProgram = useMemo(
    () => programs.find((p: ProgramResource) => p.is_active) || null,
    [programs],
  )
  const autoGeneratedProgram = useMemo(
    () =>
      programs.find((p: ProgramResource) => p.is_auto_generated && p.is_active) ||
      programs.find((p: ProgramResource) => p.is_auto_generated) ||
      null,
    [programs],
  )
  const displayWeekNumber = useMemo(
    () => activeProgram?.next_workout?.week_number ?? activeProgram?.current_active_week ?? 1,
    [activeProgram],
  )
  const activeWeekWorkouts = useMemo(() => {
    if (!activeProgram?.workout_templates) return []
    return activeProgram.workout_templates
      .filter((t: WorkoutTemplateResource) => t.week_number === displayWeekNumber)
      .sort(
        (a: WorkoutTemplateResource, b: WorkoutTemplateResource) =>
          a.order_index - b.order_index,
      )
  }, [activeProgram, displayWeekNumber])

  const defaultSelectedId = useMemo(() => {
    if (
      activeProgram?.next_workout &&
      activeWeekWorkouts.some(
        (w: WorkoutTemplateResource) => w.id === activeProgram.next_workout?.id,
      )
    ) {
      return activeProgram.next_workout.id
    }
    return activeWeekWorkouts.length > 0 ? activeWeekWorkouts[0].id : null
  }, [activeProgram, activeWeekWorkouts])

  useEffect(() => {
    if (defaultSelectedId !== null) setSelectedTemplateId(defaultSelectedId)
  }, [defaultSelectedId])

  const effectiveSelectedId = selectedTemplateId ?? defaultSelectedId

  const selectedWorkout = useMemo(
    () =>
      activeWeekWorkouts.find(
        (w: WorkoutTemplateResource) => w.id === effectiveSelectedId,
      ) || null,
    [activeWeekWorkouts, effectiveSelectedId],
  )

  const isPlanComplete = useMemo(
    () =>
      !!activeProgram &&
      activeProgram.next_workout === null &&
      (activeProgram.progress_percentage ?? 0) > 0,
    [activeProgram],
  )

  const inactiveNonAutoPrograms = useMemo(
    () => programs.filter((p: ProgramResource) => !p.is_active && !p.is_auto_generated),
    [programs],
  )

  // ─── Custom Plans tab ───
  const activePlan = useMemo(() => plans.find((p) => p.is_active) || null, [plans])
  const activePlanWorkouts = useMemo(() => {
    if (!activePlan?.workout_templates) return []
    return [...activePlan.workout_templates]
      .sort((a, b) => {
        if (a.day_of_week === null && b.day_of_week === null) return 0
        if (a.day_of_week === null) return 1
        if (b.day_of_week === null) return -1
        return a.day_of_week - b.day_of_week
      })
      .map((template) => {
        const exercises = template.exercises || []
        const mins = estimateWorkoutDuration(exercises)
        return {
          ...template,
          durationLabel: mins > 0 ? `${mins} min` : 'N/A',
          exerciseCount: exercises.length,
        }
      })
  }, [activePlan])

  // ─── Handlers ───
  const goalOptions = GOAL_OPTIONS.map((o) => ({ label: o.label, value: o.value }))
  const experienceOptions = EXPERIENCE_OPTIONS.map((o) => ({ label: o.label, value: o.value }))

  const goalLabel =
    GOAL_OPTIONS.find((o) => o.value === profile?.fitness_goal)?.label ?? 'Goal'
  const experienceLabel =
    EXPERIENCE_OPTIONS.find((o) => o.value === profile?.training_experience)?.label ??
    'Experience'
  const daysLabel = profile?.training_days_per_week
    ? `${profile.training_days_per_week} day${profile.training_days_per_week > 1 ? 's' : ''}`
    : 'Days/week'
  const durationLabel =
    DURATION_OPTIONS.find((o) => o.value === profile?.workout_duration_minutes)?.label ??
    'Duration'

  const isProfileComplete = Boolean(
    profile?.fitness_goal &&
      profile?.training_experience &&
      profile?.training_days_per_week &&
      profile?.workout_duration_minutes,
  )
  const hasCompletedWorkouts = (activeProgram?.progress_percentage ?? 0) > 0

  async function updateProfileField(
    key: 'fitness_goal' | 'training_experience' | 'training_days_per_week' | 'workout_duration_minutes',
    value: string | number,
  ) {
    try {
      await updateProfile.mutateAsync({ [key]: value } as any)
    } catch (e) {
      console.error('Failed to update profile', e)
    }
  }

  async function executeRegenerate() {
    setIsRegenerating(true)
    try {
      await regeneratePlan.mutateAsync()
    } catch (e) {
      console.error('Failed to regenerate plan', e)
    } finally {
      setIsRegenerating(false)
    }
  }

  const handleRefreshClick = () => {
    if (isRegenerating || !isProfileComplete) return
    if (!hasCompletedWorkouts) {
      executeRegenerate()
      return
    }
    Alert.alert(
      'Refresh personalized plan?',
      'Your current plan has completed workouts. Refreshing will create a new plan and you will start from scratch.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Refresh Plan', style: 'destructive', onPress: executeRegenerate },
      ],
    )
  }

  const handleStartSelectedWorkout = async () => {
    const templateId = effectiveSelectedId ?? activeProgram?.next_workout?.id
    if (!templateId) return
    try {
      const response = await startSession.mutateAsync(templateId)
      const session = (response as any).data?.session || (response as any).data
      if (session?.id) {
        if (!session.performed_at) {
          navigation.navigate('WorkoutPreview', { sessionId: String(session.id) })
        } else {
          navigation.navigate('WorkoutSession', { sessionId: String(session.id) })
        }
      }
    } catch (e) {
      console.error('Failed to start workout', e)
    }
  }

  const handleEditWorkout = (templateId: number) => {
    navigation.navigate('ManageExercises', { templateId })
  }

  const handleStartBlankSession = async () => {
    try {
      const response = await startSession.mutateAsync(undefined)
      const session = (response as any).data?.session || (response as any).data
      if (session?.id) {
        navigation.navigate('WorkoutSession', { sessionId: String(session.id) })
      }
    } catch (e) {
      console.error('Failed to start blank session', e)
    }
  }

  const handleStartPlanWorkout = async (templateId: number) => {
    try {
      const response = await startSession.mutateAsync(templateId)
      const session = (response as any).data?.session || (response as any).data
      if (session?.id) {
        navigation.navigate('WorkoutSession', { sessionId: String(session.id) })
      }
    } catch (e) {
      console.error('Failed to start workout', e)
    }
  }

  return (
    <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: colors.bgBase }}>
      <ScrollView
        contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 120 }}
        showsVerticalScrollIndicator={false}
      >
        {/* ─── Header ─── */}
        <View style={{ alignItems: 'center', paddingTop: 24, paddingBottom: 24 }}>
          {partnerLogo ? (
            <Image
              source={{ uri: partnerLogo }}
              style={{
                width: 64,
                height: 64,
                borderRadius: 16,
                marginBottom: 16,
              }}
              contentFit="contain"
              transition={200}
            />
          ) : (
            <LinearGradient
              colors={[colors.primary, colors.secondary]}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
              style={{
                width: 64,
                height: 64,
                borderRadius: 16,
                alignItems: 'center',
                justifyContent: 'center',
                marginBottom: 16,
              }}
            >
              <Dumbbell color={colors.textButton} size={32} />
            </LinearGradient>
          )}
          <GradientText style={{ fontSize: 30, fontWeight: '800' }} numberOfLines={1}>
            {partnerName}
          </GradientText>
          <Text
            style={{
              fontSize: 14,
              marginTop: 4,
              color: colors.textSecondary,
            }}
          >
            Welcome back, {user?.name || 'Athlete'}
          </Text>
        </View>

        {/* ─── Plan-type segment ─── */}
        <PlanTypeSwitcher activeType={activeTab} onTypeChange={setActiveTab} />

        {/* ═══ Programs Tab ═══ */}
        {activeTab === 'programs' && (
          <>
            {/* Program controls — chips row */}
            {autoGeneratedProgram && (
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={{
                  gap: 8,
                  paddingBottom: 16,
                  paddingHorizontal: 2,
                }}
              >
                {activeProgram?.is_active && (
                  <FilterChip
                    icon={Calendar}
                    onPress={() =>
                      navigation.navigate('ProgramDetail', { programId: activeProgram.id })
                    }
                  />
                )}
                <FilterChip
                  label={goalLabel}
                  options={goalOptions}
                  placeholder="Fitness goal"
                  onSelect={(v) => updateProfileField('fitness_goal', v)}
                />
                <FilterChip
                  label={experienceLabel}
                  options={experienceOptions}
                  placeholder="Training experience"
                  onSelect={(v) => updateProfileField('training_experience', v)}
                />
                <FilterChip
                  label={daysLabel}
                  options={DAYS_OPTIONS}
                  placeholder="Days per week"
                  onSelect={(v) => updateProfileField('training_days_per_week', v)}
                />
                <FilterChip
                  label={durationLabel}
                  options={DURATION_OPTIONS}
                  placeholder="Workout duration"
                  onSelect={(v) => updateProfileField('workout_duration_minutes', v)}
                />
                <FilterChip
                  icon={RefreshCw}
                  label="Refresh"
                  disabled={isRegenerating || !isProfileComplete}
                  onPress={handleRefreshClick}
                />
              </ScrollView>
            )}

            {isProgramsLoading ? (
              <>
                <SkeletonBox height={50} style={{ marginBottom: 12 }} />
                <SkeletonBox height={200} />
              </>
            ) : !activeProgram ? (
              <Card>
                <Text
                  style={{
                    textAlign: 'center',
                    fontWeight: '600',
                    color: colors.textPrimary,
                    marginBottom: 16,
                  }}
                >
                  No active program
                </Text>
                {inactiveNonAutoPrograms.map((prog) => (
                  <TouchableOpacity
                    key={prog.id}
                    onPress={() =>
                      navigation.navigate('ProgramDetail', { programId: prog.id })
                    }
                    style={{
                      flexDirection: 'row',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      paddingHorizontal: 16,
                      paddingVertical: 12,
                      borderRadius: 12,
                      marginBottom: 8,
                      backgroundColor: colors.bgElevated,
                      borderWidth: 1,
                      borderColor: colors.border,
                    }}
                  >
                    <Text
                      style={{ fontSize: 14, fontWeight: '600', color: colors.textPrimary }}
                    >
                      {prog.name}
                    </Text>
                    <Text style={{ fontSize: 12, color: colors.textSecondary }}>View →</Text>
                  </TouchableOpacity>
                ))}
                <TouchableOpacity
                  onPress={executeRegenerate}
                  disabled={isRegenerating || regeneratePlan.isPending}
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: 8,
                    paddingVertical: 12,
                    borderRadius: 12,
                    marginTop: 8,
                    backgroundColor: colors.primary,
                    opacity: isRegenerating ? 0.7 : 1,
                  }}
                >
                  {isRegenerating || regeneratePlan.isPending ? (
                    <ActivityIndicator size="small" color={colors.textButton} />
                  ) : (
                    <Zap size={16} color={colors.textButton} />
                  )}
                  <Text style={{ fontWeight: '600', color: colors.textButton }}>
                    Generate personalized plan
                  </Text>
                </TouchableOpacity>
              </Card>
            ) : isPlanComplete ? (
              <Card>
                <View style={{ alignItems: 'center', marginBottom: 16 }}>
                  <View
                    style={{
                      width: 64,
                      height: 64,
                      borderRadius: 32,
                      alignItems: 'center',
                      justifyContent: 'center',
                      backgroundColor: colors.bgElevated,
                    }}
                  >
                    <Trophy size={32} color={colors.primary} strokeWidth={1.75} />
                  </View>
                </View>
                <Text
                  style={{
                    fontSize: 20,
                    fontWeight: '700',
                    textAlign: 'center',
                    marginBottom: 8,
                    color: colors.textPrimary,
                  }}
                >
                  Plan complete!
                </Text>
                <Text
                  style={{
                    fontSize: 14,
                    textAlign: 'center',
                    marginBottom: 24,
                    color: colors.textSecondary,
                  }}
                >
                  You finished all {activeProgram.duration_weeks} weeks of{' '}
                  <Text style={{ fontWeight: '600', color: colors.textPrimary }}>
                    {activeProgram.name}
                  </Text>
                  .
                </Text>
                {activeProgram.is_auto_generated && (
                  <TouchableOpacity
                    onPress={executeRegenerate}
                    disabled={isRegenerating}
                    style={{
                      flexDirection: 'row',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: 8,
                      paddingVertical: 12,
                      borderRadius: 12,
                      backgroundColor: colors.primary,
                      opacity: isRegenerating ? 0.7 : 1,
                    }}
                  >
                    {isRegenerating ? (
                      <ActivityIndicator size="small" color={colors.textButton} />
                    ) : (
                      <Zap size={16} color={colors.textButton} />
                    )}
                    <Text style={{ fontWeight: '600', color: colors.textButton }}>
                      Generate new plan
                    </Text>
                  </TouchableOpacity>
                )}
              </Card>
            ) : (
              <>
                {/* Day selector */}
                {activeWeekWorkouts.length > 0 && (
                  <View style={{ marginBottom: 12 }}>
                    <WorkoutTemplateSelector
                      templates={activeWeekWorkouts}
                      selectedTemplateId={effectiveSelectedId}
                      onTemplateSelect={setSelectedTemplateId}
                      nextWorkout={activeProgram.next_workout ?? null}
                    />
                  </View>
                )}

                {/* Week indicator */}
                <Text
                  style={{
                    fontSize: 12,
                    fontWeight: '700',
                    letterSpacing: 1.2,
                    textAlign: 'center',
                    marginBottom: 16,
                    color: colors.primary,
                    textTransform: 'uppercase',
                  }}
                >
                  Week {displayWeekNumber}/{activeProgram.duration_weeks ?? '?'}
                  {activeProgram.name ? ` — ${activeProgram.name}` : ''}
                </Text>

                {/* Workout card */}
                {selectedWorkout ? (
                  <WorkoutCard
                    template={selectedWorkout}
                    title={selectedWorkout.name || 'WORKOUT'}
                    showStartButton
                    startButtonText={effectiveSelectedId ? 'START WORKOUT' : 'NO WORKOUTS AVAILABLE'}
                    startButtonDisabled={!effectiveSelectedId}
                    startButtonLoading={startSession.isPending}
                    onStartNextWorkout={handleStartSelectedWorkout}
                    onExerciseClick={(name) =>
                      navigation.navigate('ExerciseDetail', { exerciseName: name })
                    }
                    onEditWorkout={handleEditWorkout}
                  />
                ) : (
                  <Card>
                    <Text style={{ textAlign: 'center', color: colors.textSecondary }}>
                      No workouts available for this week
                    </Text>
                  </Card>
                )}
              </>
            )}
          </>
        )}

        {/* ═══ Custom Plans Tab ═══ */}
        {activeTab === 'customPlans' && (
          <>
            {/* AI Generator Card — matches web AIGeneratorCard */}
            <View
              style={{
                borderRadius: 16,
                padding: 24,
                marginBottom: 32,
                overflow: 'hidden',
                position: 'relative',
                backgroundColor: colors.primary,
              }}
            >
              {/* Background decoration circle */}
              <View
                style={{
                  position: 'absolute',
                  top: -40,
                  right: -40,
                  width: 128,
                  height: 128,
                  borderRadius: 64,
                  backgroundColor: 'rgba(255,255,255,0.1)',
                }}
              />

              {/* "Fit Nation Engine" label */}
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <Zap size={16} color={colors.secondary} fill={colors.secondary} />
                <Text
                  style={{
                    fontSize: 11,
                    fontWeight: '700',
                    letterSpacing: 1.5,
                    textTransform: 'uppercase',
                    color: colors.secondary,
                  }}
                >
                  Fit Nation Engine
                </Text>
              </View>

              <Text
                style={{ fontSize: 20, fontWeight: '700', marginBottom: 8, color: colors.textButton }}
              >
                Not sure what to do?
              </Text>
              <Text
                style={{
                  fontSize: 14,
                  marginBottom: 24,
                  lineHeight: 20,
                  opacity: 0.8,
                  color: colors.textButton,
                }}
              >
                Let our AI generate a perfect workout based on your recovery and goals.
              </Text>

              <TouchableOpacity
                onPress={() => navigation.navigate('GenerateWorkout')}
                style={{
                  paddingVertical: 12,
                  paddingHorizontal: 16,
                  borderRadius: 12,
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  borderWidth: 1,
                  borderColor: 'rgba(255,255,255,0.2)',
                  backgroundColor: 'rgba(255,255,255,0.05)',
                }}
              >
                <Text style={{ fontSize: 14, fontWeight: '600', color: colors.textButton }}>
                  Generate Smart Workout
                </Text>
                <ChevronRight size={16} color={colors.textButton} strokeWidth={2} />
              </TouchableOpacity>
            </View>

            {/* Recommended Routines */}
            {browsableRoutines.length > 0 && (
              <>
                <View
                  style={{
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: 16,
                    paddingHorizontal: 4,
                  }}
                >
                  <Text style={{ fontSize: 18, fontWeight: '700', color: colors.primary }}>
                    Recommended Workouts
                  </Text>
                </View>
                <ScrollView
                  horizontal
                  showsHorizontalScrollIndicator={false}
                  contentContainerStyle={{ gap: 12, paddingBottom: 8 }}
                >
                  {browsableRoutines.map((routine) => (
                    <TouchableOpacity
                      key={routine.id}
                      activeOpacity={0.85}
                      onPress={() =>
                        navigation.navigate('RoutineDetail', { routineId: routine.id })
                      }
                      style={{
                        width: 200,
                        borderRadius: 16,
                        overflow: 'hidden',
                        backgroundColor: colors.bgSurface,
                      }}
                    >
                      {/* Cover image area (h-28 equivalent = 112) */}
                      <View style={{ width: '100%', height: 112, overflow: 'hidden' }}>
                        {routine.cover_image ? (
                          <>
                            <Image
                              source={{ uri: routine.cover_image }}
                              style={{ width: '100%', height: '100%' }}
                              contentFit="cover"
                            />
                            <LinearGradient
                              colors={['transparent', 'rgba(0,0,0,0.5)']}
                              style={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }}
                            />
                          </>
                        ) : (
                          <LinearGradient
                            colors={[colors.bgElevated, colors.bgSurface]}
                            start={{ x: 0, y: 0 }}
                            end={{ x: 1, y: 1 }}
                            style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}
                          >
                            <Dumbbell size={40} color={colors.textMuted} />
                          </LinearGradient>
                        )}
                      </View>
                      {/* Info */}
                      <View style={{ padding: 12 }}>
                        <Text
                          numberOfLines={1}
                          style={{
                            fontSize: 14,
                            fontWeight: '700',
                            marginBottom: 4,
                            color: colors.textPrimary,
                          }}
                        >
                          {routine.name}
                        </Text>
                        <Text style={{ fontSize: 12, color: colors.textSecondary }}>
                          {routine.workout_templates?.length ?? 0}{' '}
                          {(routine.workout_templates?.length ?? 0) === 1 ? 'workout' : 'workouts'}
                        </Text>
                      </View>
                    </TouchableOpacity>
                  ))}
                </ScrollView>
                <View style={{ marginBottom: 32 }} />
              </>
            )}

            {/* Active Plan Workouts Section */}
            <View
              style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: 16,
                paddingHorizontal: 4,
              }}
            >
              <Text style={{ fontSize: 18, fontWeight: '700', color: colors.primary }}>
                {activePlan ? activePlan.name : 'My Custom Plans'}
              </Text>
              {activePlan && (
                <TouchableOpacity onPress={() => navigation.navigate('Tabs')}>
                  <Text style={{ fontSize: 14, color: colors.textSecondary }}>See all</Text>
                </TouchableOpacity>
              )}
            </View>

            {isPlansLoading ? (
              <SkeletonBox height={100} style={{ marginBottom: 16 }} />
            ) : activePlan && activePlanWorkouts.length > 0 ? (
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={{ gap: 16, paddingBottom: 8 }}
              >
                {activePlanWorkouts.map((workout) => (
                  <View
                    key={workout.id}
                    style={{
                      width: 180,
                      borderRadius: 16,
                      padding: 20,
                      backgroundColor: colors.bgSurface,
                      flexDirection: 'column',
                    }}
                  >
                    {/* Icon circle */}
                    <View
                      style={{
                        width: 40,
                        height: 40,
                        borderRadius: 20,
                        alignItems: 'center',
                        justifyContent: 'center',
                        marginBottom: 16,
                        backgroundColor: `${colors.primary}1A`,
                      }}
                    >
                      <Dumbbell size={18} color={colors.primary} />
                    </View>

                    <TouchableOpacity
                      onPress={() => navigation.navigate('EditWorkout', { templateId: workout.id })}
                    >
                      <Text
                        numberOfLines={2}
                        style={{
                          fontSize: 18,
                          fontWeight: '700',
                          marginBottom: 12,
                          color: colors.primary,
                        }}
                      >
                        {workout.name}
                      </Text>
                    </TouchableOpacity>

                    {/* Stats row */}
                    <View
                      style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                        gap: 12,
                        marginTop: 'auto' as any,
                        marginBottom: 12,
                      }}
                    >
                      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
                        <Clock size={12} color={colors.textSecondary} />
                        <Text style={{ fontSize: 12, fontWeight: '500', color: colors.textSecondary }}>
                          {workout.durationLabel}
                        </Text>
                      </View>
                      <View
                        style={{
                          width: 4,
                          height: 4,
                          borderRadius: 2,
                          backgroundColor: colors.borderSubtle,
                        }}
                      />
                      <Text style={{ fontSize: 12, fontWeight: '500', color: colors.textSecondary }}>
                        {workout.exerciseCount} Ex
                      </Text>
                    </View>

                    <TouchableOpacity
                      onPress={() => handleStartPlanWorkout(workout.id)}
                      disabled={startSession.isPending}
                      style={{
                        paddingVertical: 8,
                        borderRadius: 12,
                        alignItems: 'center',
                        backgroundColor: colors.primary,
                      }}
                    >
                      <Text style={{ fontSize: 12, fontWeight: '600', color: colors.textButton }}>
                        Start
                      </Text>
                    </TouchableOpacity>
                  </View>
                ))}
              </ScrollView>
            ) : (
              <View style={{ paddingHorizontal: 4 }}>
                <TouchableOpacity
                  onPress={() => navigation.navigate('CreatePlan')}
                  style={{
                    width: 160,
                    borderRadius: 16,
                    padding: 20,
                    alignItems: 'center',
                    justifyContent: 'center',
                    minHeight: 140,
                    backgroundColor: colors.bgSurface,
                    borderWidth: 2,
                    borderStyle: 'dashed',
                    borderColor: colors.borderSubtle,
                  }}
                >
                  <View
                    style={{
                      width: 48,
                      height: 48,
                      borderRadius: 24,
                      alignItems: 'center',
                      justifyContent: 'center',
                      marginBottom: 12,
                      backgroundColor: colors.borderSubtle,
                    }}
                  >
                    <Plus size={24} color={colors.textSecondary} />
                  </View>
                  <Text style={{ fontSize: 14, fontWeight: '500', color: colors.textSecondary }}>
                    Create New
                  </Text>
                </TouchableOpacity>
              </View>
            )}

            <View style={{ marginBottom: 32 }} />

            {/* Quick Start Card — matches web QuickStartCard */}
            <View
              style={{
                borderRadius: 16,
                padding: 24,
                marginBottom: 16,
                overflow: 'hidden',
                backgroundColor: colors.bgSurface,
                borderWidth: 1,
                borderColor: colors.borderSubtle,
              }}
            >
              <View
                style={{
                  flexDirection: 'row',
                  justifyContent: 'space-between',
                  alignItems: 'flex-start',
                  marginBottom: 8,
                }}
              >
                <View>
                  <Text style={{ fontSize: 20, fontWeight: '700', color: colors.primary }}>
                    Quick Start
                  </Text>
                  <Text style={{ fontSize: 14, marginTop: 4, color: colors.textSecondary }}>
                    Start a blank session without a plan
                  </Text>
                </View>
              </View>

              <TouchableOpacity
                onPress={handleStartBlankSession}
                disabled={startSession.isPending}
                activeOpacity={0.9}
                style={{
                  height: 48,
                  borderRadius: 12,
                  overflow: 'hidden',
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: 8,
                  marginTop: 24,
                  opacity: startSession.isPending ? 0.7 : 1,
                }}
              >
                <LinearGradient
                  colors={[colors.secondary, colors.primary]}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                  style={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }}
                />
                {startSession.isPending ? (
                  <ActivityIndicator color={colors.textButton} />
                ) : (
                  <>
                    <Play size={18} color={colors.textButton} fill={colors.textButton} />
                    <Text style={{ fontSize: 16, fontWeight: '700', color: colors.textButton }}>
                      Start Blank Session
                    </Text>
                  </>
                )}
              </TouchableOpacity>
            </View>
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  )
}
